image
  name registry.gitlab.comgitlab-orgterraform-imagesstablelatest
  entrypoint
    - 'usrbinenv'
    - 'PATH=usrlocalsbinusrlocalbinusrsbinusrbinsbinbin'
    - 'AWS_ACCESS_KEY_ID=AKIAV6SP633MR3ARM7FE' 
    - 'AWS_SECRET_ACCESS_KEY=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' 

variables
  TF_ROOT $CI_PROJECT_DIRterraform

before_script
  - cd ${TF_ROOT}
  - rm -rf .terraform
  - terraform --version
  - terraform init 
  

##add1, add2 manuell auf client ausgefuehrt
stages
  - validate
  - plan
  - build
  - destroy

validate
  stage validate
  script
    - terraform validate

plan
  stage plan
  script
    - terraform plan -input=false -out=tf.plan
  dependencies 
    - validate
  artifacts
    paths
      - ${TF_ROOT}tf.plan

apply
  stage build
  script
    - terraform apply -input=false tf.plan

  dependencies
    - plan
  when manual

destroy
  stage destroy
  script
    - terraform destroy -auto-approve
  dependencies
    - apply
  when manual
