apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonacci-app
  template:
    metadata:
      labels:
        app: fibonacci-app
    spec:
      containers:
      - name: fibonacci-app
        image: globdo/bt:fibonacci
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8090 # The port that the container is running on in the cluster
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"      
  
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: fibonacci-vpa
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders: 
  #   - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: fibonacci-app
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 200Mi
        maxAllowed:
          cpu: 1500m
          memory: 1500Mi
        controlledResources: ["cpu", "memory"]
          
