apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  labels:
    app: fibonacci-app
spec:
  type: ClusterIP
  selector:
    app: fibonacci-app
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer
#unique IP address that can be reached from any node or pod 
#within the cluster, but it can't be reached from outside of 
#the cluster. The values for Endpoints are IP addresses assigned 
#from within your VPC to the pods that are part of the service.